// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADoVRf856PGf7eH6Mabry1SdTmSIstTLs',
    appId: '1:671738204587:web:702cde084e50d46efa42ee',
    messagingSenderId: '671738204587',
    projectId: 'udelivery-71481',
    authDomain: 'udelivery-71481.firebaseapp.com',
    storageBucket: 'udelivery-71481.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5HkJ44VEYBKGv3laJ4bVqJS4y-cAXfB0',
    appId: '1:671738204587:android:11898b54d0266f6efa42ee',
    messagingSenderId: '671738204587',
    projectId: 'udelivery-71481',
    storageBucket: 'udelivery-71481.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5JRwFYvgexw1EXFETEqhoWZZcVEhpvw',
    appId: '1:671738204587:ios:247356823da570bffa42ee',
    messagingSenderId: '671738204587',
    projectId: 'udelivery-71481',
    storageBucket: 'udelivery-71481.appspot.com',
    iosClientId: '671738204587-54n164haod6j98rtgnliotf9nve0rh5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.udelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx5JRwFYvgexw1EXFETEqhoWZZcVEhpvw',
    appId: '1:671738204587:ios:247356823da570bffa42ee',
    messagingSenderId: '671738204587',
    projectId: 'udelivery-71481',
    storageBucket: 'udelivery-71481.appspot.com',
    iosClientId: '671738204587-54n164haod6j98rtgnliotf9nve0rh5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.udelivery',
  );
}
